# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/16_accel_sgd.ipynb.

# %% auto 0
__all__ = []

# %% ../nbs/16_accel_sgd.ipynb 1
import pickle,gzip,math,os,time,shutil,torch,matplotlib as mpl,numpy as np,matplotlib.pyplot as plt
import fastcore.all as fc
from collections.abc import Mapping
from pathlib import Path
from operator import attrgetter,itemgetter
from functools import partial
from copy import copy
from contextlib import contextmanager

from torch import tensor,nn,optim
from torch.utils.data import DataLoader,default_collate
import torch.nn.functional as F
import torchvision.transforms.functional as TF
from datasets import load_dataset,load_dataset_builder
from torcheval.metrics import MulticlassAccuracy

from .datasets import *
from .conv import *
from .learner import *
from .activations import *

from fastprogress import progress_bar,master_bar
